import './globals.scss'
import type { Metadata } from 'next'
import Helmet from "@/components/global/Helmet";
import Aside from "@/components/global/Aside";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flow-container">
          <Helmet />
          <Aside />
          <div className="container">
            <Header />
            {children}
          </div>
          <Footer />
      </main>
     </body>
    </html>
  )
}

// import React, { ReactNode } from "react";

// import Helmet from "@/components/global/Helmet";
// import Aside from "@/components/global/Aside";
// import Header from "@/components/global/Header";
// import Footer from "@/components/global/Footer";

// type Props = {
//   children: ReactNode;
// };

// export default function Layout({ children }: Props) {
//   return (
//     <main className="flow-container">
//       <Helmet />
//       <Aside />
//       <div className="container">
//         <Header />
//         {children}
//       </div>
//       <Footer />
//     </main>
//   );
// }

