import "./globals.scss";
import type { Metadata } from "next";
import Aside from "@/components/global/Aside";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";
import ReactQueryPropvider from "@/components/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryPropvider>
          <main className="flow-container">
            <Aside />
            <div className="container">
              <Header />
              {children}
            </div>
            <Footer />
          </main>
        </ReactQueryPropvider>
      </body>
    </html>
  );
}